name: MuseTalk
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pip
  - numpy=1.23.5
  - opencv
  - ffmpeg
  - pip:
    - fastapi
    - uvicorn
    - python-multipart
    - websockets
    - pydantic
    - tensorflow==2.12.0
    - tensorboard==2.12.0
    - accelerate==0.28.0
    - diffusers==0.30.2
    - transformers==4.39.2
    - einops==0.8.1
    - gradio==5.24.0
    - gdown
    - requests
    - imageio[ffmpeg]
    - omegaconf
    - ffmpeg-python
    - moviepy
    - librosa==0.11.0
    - soundfile==0.12.1
    - huggingface_hub==0.30.2
